Página contacto creada como componente
johneospina18/fundacion-promesas-de-cristo pull request #27
Opened 2023-01-03 03:36 UTC by johneospina18

Nico,
Traté de dejar enrutado de una vez con el menú a través de youtube pero fallé en el intento, mi conocimiento aún no llega a esos espacios, sin embargo, le solicito respetuosamente que me ayude a hacer esto por favor.
Gracias

2023-01-07 16:30 UTC, johneospina18 commented
Nico hola, he creado dos nuevos componentes: 
-Encabezado
-box-messages 
Cometí el error de colocar el componente encabezado en español  al igual que el contacto-page, también cabe destacar que solo creé dos componentes por lo tanto no agregué tareas.
Otro error que cometí es que no sé como crear componentes directamente en la carpeta, entonces quedaron por fuera, no me atreví aún a meterlos dentro de la carpeta componentes porque no sé si genere algún inconveniente, por favor, cuando tenga tiempo me explica como solucionar esto.
Eso en términos generales del contacto-page.
Quedo atento, gracias

2023-01-09 15:52 UTC, nicomix requested changes
@johneospina18 Por qué separó encabezado component? El nombre se podría corregir con el comando `git mv` y luego cambiando dentro de los archivos los nombres necesarios.

El nombre del componente box messages no tiene mucho sentido, me gustaría una explicación mas extendida sobre el porque se llama así y cual es su objetivo ya que contiene formulario, títulos, botones, etc. El mismo componente tiene un formulario, ese formulario podría ir en un componente aparte llamado `ContactForm` en el cual implemente ReactiveForm de angular.

2023-01-09 15:52 UTC, nicomix commented on src/app/box-messages/box-messages.component.html
> +    <div class="container" id="principalBox">
@johneospina18 debería usar en este formulario componentes nativos de Angular que nos facilitan ciertas tareas, le recomiendo implemente un ReactiveForm, busque acerca de reactive forms en la documentación de Angular

2023-01-09 15:55 UTC, nicomix requested changes
@johneospina18 inglés o español? Cual usamos? No hagamos espanglish en el código

2023-01-09 15:55 UTC, nicomix commented on src/app/pages/contacto-page/contacto-page.component.ts
> +export class ContactoPageComponent implements OnInit {
@johneospina18 vamos a usar el español o el inglés para nombrar componentes? Si es en inglés debería llamarse `ContactPageComponent`

2023-01-09 15:55 UTC, nicomix commented on src/app/encabezado/encabezado.component.ts
> +export class EncabezadoComponent implements OnInit {
@johneospina18 lo mismo acá, inglés o español?

2023-01-09 15:55 UTC, nicomix commented on src/app/app-routing.module.ts
> +    path:"contacto",
Lo mismo acá en cuanto al idioma

2023-01-16 22:38 UTC, johneospina18 commented
@nicomix He realizado los cambios de los componentes que estaban en español por nombres en inglés, he implementado reactive forms, he mejorado con bootstrap el responsive de la página, adicionalmente, implementé una alerta de bootstrap para mostrar cuando no se han completado los espacios para llenar, el botón de enviar se pone en gris cuando se no están llenos correctamente los espacios del formulario, pero el botón por ahora solo genera un .json en consola que muestra el contenido del mensaje, el nombre, el asunto y el email. 
Quedo atento, gracias.

2023-02-10 19:51 UTC, merged